#!/usr/bin/env python3
"""
Visualize Surface Detection Results from Step 3 and Step 3.1

Reads CSV files generated by step3_rotation_z.py and creates detailed visualizations
for debugging and verification of surface detection and alignment.

Usage:
    python visualize_surfaces.py <data_dir>
    python visualize_surfaces.py C:/path/to/output/folder

The script looks for:
    - step3_surfaces.csv
    - step3_1_surfaces.csv
"""

import sys
import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def visualize_step3_surfaces(csv_path, output_path=None):
    """
    Visualize Step 3 surface detection results.

    Shows:
    - All three surfaces (ref, mov_before, mov_after)
    - Surface differences before/after rotation
    - Edge margin regions
    """
    df = pd.read_csv(csv_path)

    x = df['x'].values
    surface_ref = df['surface_ref'].values
    surface_mov_before = df['surface_mov_before'].values
    surface_mov_after = df['surface_mov_after'].values
    edge_margin = df['edge_margin_px'].iloc[0]
    rotation_angle = df['rotation_angle_deg'].iloc[0]

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle(f'Step 3 Surface Analysis (Rotation: {rotation_angle:+.2f}°, Edge Margin: {edge_margin}px)',
                 fontsize=14, fontweight='bold')

    # Top-left: All surfaces
    ax = axes[0, 0]
    ax.plot(x, surface_ref, 'g-', linewidth=1.5, label='Reference', alpha=0.8)
    ax.plot(x, surface_mov_before, 'r--', linewidth=1.5, label='Moving (before rotation)', alpha=0.7)
    ax.plot(x, surface_mov_after, 'b-', linewidth=1.5, label='Moving (after rotation)', alpha=0.8)
    if edge_margin > 0:
        ax.axvspan(0, edge_margin, alpha=0.2, color='yellow', label=f'Edge margin ({edge_margin}px)')
        ax.axvspan(len(x) - edge_margin, len(x), alpha=0.2, color='yellow')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Y (pixels)')
    ax.set_title('All Surfaces')
    ax.legend(loc='upper right')
    ax.invert_yaxis()
    ax.grid(True, alpha=0.3)

    # Top-right: Difference before rotation
    ax = axes[0, 1]
    diff_before = surface_ref - surface_mov_before
    ax.plot(x, diff_before, 'r-', linewidth=1, alpha=0.8)
    ax.axhline(y=0, color='k', linestyle='--', linewidth=0.5)
    ax.axhline(y=np.median(diff_before), color='r', linestyle=':', linewidth=1,
               label=f'Median: {np.median(diff_before):.1f}px')
    if edge_margin > 0:
        ax.axvspan(0, edge_margin, alpha=0.2, color='yellow')
        ax.axvspan(len(x) - edge_margin, len(x), alpha=0.2, color='yellow')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Difference (ref - mov) [pixels]')
    ax.set_title(f'Surface Difference BEFORE Rotation (std={np.std(diff_before):.1f}px)')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    # Bottom-left: Difference after rotation
    ax = axes[1, 0]
    diff_after = surface_ref - surface_mov_after
    ax.plot(x, diff_after, 'b-', linewidth=1, alpha=0.8)
    ax.axhline(y=0, color='k', linestyle='--', linewidth=0.5)
    ax.axhline(y=np.median(diff_after), color='b', linestyle=':', linewidth=1,
               label=f'Median: {np.median(diff_after):.1f}px')
    if edge_margin > 0:
        ax.axvspan(0, edge_margin, alpha=0.2, color='yellow')
        ax.axvspan(len(x) - edge_margin, len(x), alpha=0.2, color='yellow')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Difference (ref - mov) [pixels]')
    ax.set_title(f'Surface Difference AFTER Rotation (std={np.std(diff_after):.1f}px)')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    # Bottom-right: Histogram of differences
    ax = axes[1, 1]
    ax.hist(diff_before, bins=50, alpha=0.5, color='red', label=f'Before (std={np.std(diff_before):.1f})')
    ax.hist(diff_after, bins=50, alpha=0.5, color='blue', label=f'After (std={np.std(diff_after):.1f})')
    ax.axvline(x=0, color='k', linestyle='--', linewidth=1)
    ax.set_xlabel('Difference (ref - mov) [pixels]')
    ax.set_ylabel('Count')
    ax.set_title('Distribution of Surface Differences')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"[SAVED] {output_path}")
    else:
        plt.show()

    plt.close(fig)

    # Print statistics
    print(f"\n=== Step 3 Surface Statistics ===")
    print(f"Rotation angle: {rotation_angle:+.2f}°")
    print(f"Edge margin: {edge_margin}px")
    print(f"Total points: {len(x)}")
    print(f"Valid points (excluding margins): {len(x) - 2*edge_margin}")
    print(f"\nBEFORE rotation:")
    print(f"  Mean diff: {np.mean(diff_before):.2f}px")
    print(f"  Median diff: {np.median(diff_before):.2f}px")
    print(f"  Std diff: {np.std(diff_before):.2f}px")
    print(f"\nAFTER rotation:")
    print(f"  Mean diff: {np.mean(diff_after):.2f}px")
    print(f"  Median diff: {np.median(diff_after):.2f}px")
    print(f"  Std diff: {np.std(diff_after):.2f}px")
    print(f"\nImprovement: std {np.std(diff_before):.2f} -> {np.std(diff_after):.2f} ({np.std(diff_after) - np.std(diff_before):+.2f}px)")


def visualize_step3_1_surfaces(csv_path, output_path=None):
    """
    Visualize Step 3.1 surface detection results.

    Shows:
    - Reference and rotated moving surfaces
    - Surface difference
    - Y-shift correction applied
    """
    df = pd.read_csv(csv_path)

    x = df['x'].values
    surface_ref = df['surface_ref'].values
    surface_mov = df['surface_mov_rotated'].values
    diff = df['diff'].values
    y_shift = df['y_shift_correction'].iloc[0]
    edge_margin = df['edge_margin_px'].iloc[0]

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle(f'Step 3.1 Surface Analysis (Y-Shift: {y_shift:+.2f}px, Edge Margin: {edge_margin}px)',
                 fontsize=14, fontweight='bold')

    # Top-left: Both surfaces
    ax = axes[0, 0]
    ax.plot(x, surface_ref, 'g-', linewidth=1.5, label='Reference', alpha=0.8)
    ax.plot(x, surface_mov, 'b-', linewidth=1.5, label='Moving (after rotation)', alpha=0.8)
    if edge_margin > 0:
        ax.axvspan(0, edge_margin, alpha=0.2, color='yellow', label=f'Edge margin ({edge_margin}px)')
        ax.axvspan(len(x) - edge_margin, len(x), alpha=0.2, color='yellow')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Y (pixels)')
    ax.set_title('Surfaces Before Y-Correction')
    ax.legend(loc='upper right')
    ax.invert_yaxis()
    ax.grid(True, alpha=0.3)

    # Top-right: Surfaces after Y-correction
    ax = axes[0, 1]
    surface_mov_corrected = surface_mov + y_shift
    ax.plot(x, surface_ref, 'g-', linewidth=1.5, label='Reference', alpha=0.8)
    ax.plot(x, surface_mov_corrected, 'b--', linewidth=1.5, label=f'Moving (shifted {y_shift:+.1f}px)', alpha=0.8)
    if edge_margin > 0:
        ax.axvspan(0, edge_margin, alpha=0.2, color='yellow')
        ax.axvspan(len(x) - edge_margin, len(x), alpha=0.2, color='yellow')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Y (pixels)')
    ax.set_title('Surfaces After Y-Correction')
    ax.legend(loc='upper right')
    ax.invert_yaxis()
    ax.grid(True, alpha=0.3)

    # Bottom-left: Surface difference
    ax = axes[1, 0]
    ax.plot(x, diff, 'b-', linewidth=1, alpha=0.8)
    ax.axhline(y=0, color='k', linestyle='--', linewidth=0.5)
    ax.axhline(y=np.median(diff), color='b', linestyle=':', linewidth=1,
               label=f'Median: {np.median(diff):.1f}px = Y-shift')
    if edge_margin > 0:
        ax.axvspan(0, edge_margin, alpha=0.2, color='yellow', label=f'Edge margin ({edge_margin}px)')
        ax.axvspan(len(x) - edge_margin, len(x), alpha=0.2, color='yellow')
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Difference (ref - mov) [pixels]')
    ax.set_title(f'Surface Difference (std={np.std(diff):.1f}px)')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    # Bottom-right: Histogram
    ax = axes[1, 1]
    ax.hist(diff, bins=50, alpha=0.7, color='blue', edgecolor='black')
    ax.axvline(x=np.median(diff), color='r', linestyle='--', linewidth=2,
               label=f'Median: {np.median(diff):.1f}px')
    ax.axvline(x=np.mean(diff), color='orange', linestyle=':', linewidth=2,
               label=f'Mean: {np.mean(diff):.1f}px')
    ax.set_xlabel('Difference (ref - mov) [pixels]')
    ax.set_ylabel('Count')
    ax.set_title('Distribution of Surface Differences')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"[SAVED] {output_path}")
    else:
        plt.show()

    plt.close(fig)

    # Print statistics
    print(f"\n=== Step 3.1 Surface Statistics ===")
    print(f"Y-shift correction: {y_shift:+.2f}px")
    print(f"Edge margin: {edge_margin}px")
    print(f"Total points: {len(x)}")
    print(f"Valid points (excluding margins): {len(x) - 2*edge_margin}")
    print(f"\nSurface difference:")
    print(f"  Mean: {np.mean(diff):.2f}px")
    print(f"  Median: {np.median(diff):.2f}px (used as Y-shift)")
    print(f"  Std: {np.std(diff):.2f}px")
    print(f"  Min: {np.min(diff):.2f}px")
    print(f"  Max: {np.max(diff):.2f}px")


def main():
    parser = argparse.ArgumentParser(
        description='Visualize surface detection results from Step 3 and Step 3.1'
    )
    parser.add_argument('data_dir', type=str, help='Directory containing CSV files')
    parser.add_argument('--save', action='store_true', help='Save visualizations to files')

    args = parser.parse_args()
    data_dir = Path(args.data_dir)

    if not data_dir.exists():
        print(f"Error: Directory not found: {data_dir}")
        sys.exit(1)

    # Look for Step 3 CSV
    step3_csv = data_dir / "step3_surfaces.csv"
    if step3_csv.exists():
        print(f"\n{'='*60}")
        print(f"Processing Step 3: {step3_csv}")
        print(f"{'='*60}")
        output_path = data_dir / "step3_surfaces_analysis.png" if args.save else None
        visualize_step3_surfaces(step3_csv, output_path)
    else:
        print(f"Step 3 CSV not found: {step3_csv}")

    # Look for Step 3.1 CSV
    step3_1_csv = data_dir / "step3_1_surfaces.csv"
    if step3_1_csv.exists():
        print(f"\n{'='*60}")
        print(f"Processing Step 3.1: {step3_1_csv}")
        print(f"{'='*60}")
        output_path = data_dir / "step3_1_surfaces_analysis.png" if args.save else None
        visualize_step3_1_surfaces(step3_1_csv, output_path)
    else:
        print(f"Step 3.1 CSV not found: {step3_1_csv}")

    print(f"\n{'='*60}")
    print("Done!")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
